### ISSUE TITLE
麻烦支持下OSS 创建软连接:  ObjectCreated:PutSymlink

### ISSUE THREAD

**Issue by rsonghuster** [awesome-fnf/oss-unzip#1]
https://yq.aliyun.com/articles/680958

![image](https://user-images.githubusercontent.com/10919599/74134161-fddeeb80-4c24-11ea-8a02-51bfd867edcf.png)

**Comment by wanghq** [comment]
Done

https://github.com/awesome-fnf/oss-unzip/commit/3df2a3377ef37a1c96ba14783ba31711ff423793#diff-f82031d035f05e41771af021f974bacb
